### PR TITLE
Improve the Reproducibility of the Codebase

### PR DESCRIPTION
**Pull request by ahaim5357**
Updates the codebase to have a reproducible environment using dev containers and Docker. This method is further explained in `README`. If the user chooses not to use dev containers, a basic explanation for running the code locally is also provided.

The only part of the process that couldn't be automated was grabbing the datasets and transactions from DataShop as the Web Services API did not support it. Technically, transactions could be pulled iteratively, but the process for exporting is simple enough that a user shouldn't have any trouble executing it.

As I also couldn't run `process-transcripts.ipynb`, I did not setup anything related to using the GPU to run the codebase.

### CODE REVIEW

**Comment by conradborchers** [comment]
Thanks, Aaron! I appreciate this work and I can learn a lot from it it seems. Happy to merge after processing the following.

I tried the following and received an error on my machine. Is `{tidyverse}` perhaps missing from the renv?

```
 srl-cycles-lak24 % Rscript ./setup-lak24.R 
# Bootstrapping renv 1.0.7 [sha: 265a038] ------------------------------------
- Downloading renv ... OK
- Installing renv  ... OK

- One or more packages recorded in the lockfile are not installed.
- Use `renv::status()` for more details.
Error in library(tidyverse) : there is no package called ‘tidyverse’
Execution halted
```

Also, it seems like your regex to check whether the TX file is present in the WD is not working on my Mac. How about using something that does not depend on OS-specific regex defaults like checking for returns on `ls ds5371*.txt`.

Kindly check -- thank you

**Comment by ahaim5357** [comment]
> I tried the following and received an error on my machine. Is `{tidyverse}` perhaps missing from the renv?

No, the script does not run `renv::restore`, so the dependencies are not installed. That is why I specified in the README that the command be run manually. I don't think there's any harm in running the command in the script, it just seems odd in my head.

> Also, it seems like your regex to check whether the TX file is present in the WD is not working on my Mac. How about using something that does not depend on OS-specific regex defaults like checking for returns on ls ds5371*.txt.

The shell script was only meant to work on Linux environments since it was supposed to automate the dev container process, which is what the note states. However, I will work on removing the dependency for all Unix environments if that's what you wish.

**Comment by conradborchers** [comment]
Gotcha! Thanks for clarifying, I appreciate it.

Could we add `brew install rename` to the installation of rename or (perhaps even better) use mv instead of rename? Is there an advantage to using rename over mv?

Also, during installing R packages with renv (error-prone as you say it in the README but certainly more accessible for researchers with no Docker experience) we might want to up the `ferror-limit` argument. Installation of `{MASS}` fails for me:

```
fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

These warnings in source code are common for R packages.

I will merge once I can get a clean install on my Mac. I could also see making renv optional (for people who want to run the code primarily rather than reproducing results). Would that be possible? What do you think of that?

Thanks again

**Comment by ahaim5357** [comment]
> Could we add `brew install rename` to the installation of rename or (perhaps even better) use mv instead of rename? Is there an advantage to using rename over mv?

I believe that should work for Mac based on some headers. The reason I used `rename` over `mv` is to support regex grouping for renames. The command functions nicely to strip all transaction files of their timestamps while keeping the name the same. However, I can write a loop with `sed` that does something similar to avoid the dependency.

> Also, during installing R packages with renv (error-prone as you say it in the README but certainly more accessible for researchers with no Docker experience) we might want to up the ferror-limit argument. Installation of {MASS} fails for me:

So, that is an error with your underlying C compiler that is trying to compile the package from source. That means that it wasn't able to install the binary, which is problematic as that would indicate your Mac setup is different than what is normally supported. However, with a bit of research, there apparently are a bunch of issues when trying to [compile packages from source on a Mac](https://rodzepeda.medium.com/fixing-macos-catalinas-mess-when-trying-to-compile-almost-any-r-package-d94a063d64eb).

> I could also see making renv optional (for people who want to run the code primarily rather than reproducing results). Would that be possible? What do you think of that?

I mean, renv is not specifically for reproducibility. That's just a benefit. renv is supposed to install the packages used so that you can actually run someone else's code. R packages are generally not compatible across different versions. For example, the `alpha.correction.bh` package that was originally in your codebase only worked on 4.2.0, not 4.2.1-4.2.3, which is a major issue.

This is the reason why I like development environments. They basically setup a linux operating system, install the necessary languages you need, and can be shipped across machines with a relatively solid level of consistency. Everyone will have the same setup, so unless your computer has a hardware bug or a completely different implementation of the available instruction codes, it will usually work without issue.

For reference, I don't have any programming language directly on my computer. They are all in a development environment as I can just download the repository on a different computer, and the environment works without major concern. I tested all this codebase across Windows, Mac, and Linux in the development environment, and it worked perfectly without issues, allowing me to run the code. Honestly, the only difficulty about not using Docker Desktop or VSCode nowadays is if you can't install software on a computer you know how to use. Development environments also have a pretty simple setup process as you can generally type in what you want into a search bar and it will generate the necessary files for you. But I digress; this is just my opinion on the matter.

**Comment by conradborchers** [comment]
Thanks! I would think `sed` and compatibility is > elegance of code in this case. I appreciate the revision -- this DataShop timestamp dependency is something I would include in other repos as well.

Regarding installing from source on Mac, I can confirm that `install.packages('MASS')` works fine when doing so in the console but not through `renv::restore(prompt = FALSE)`. Maybe it's easier if we allow an installation that's not from source? I wonder.

I certainly agree that a virtual environment is better and more robust. At the same time, I would think that most researchers using the code will not have experience setting it up or not want the 15-45 min wait before running the code. I see a tradeoff here; and for merging to main it would be great to have the option to skip setting up the renv. Right now, when I clone the repo it seems that I am forced to use renv to run R. I wonder if that could be made optional in a convenient way. To support both quick use and precision for reproducibility.

Let me know how we can best work on making the merge happen. Thanks again!

**Comment by ahaim5357** [comment]
> Regarding installing from source on Mac, I can confirm that `install.packages('MASS')` works fine when doing so in the console but not through `renv::restore(prompt = FALSE)`. Maybe it's easier if we allow an installation that's not from source? I wonder.

I think I have an idea on what's causing the issue. renv is using 4.2.3 to download and compile the packages while you are on 4.2.0. R 4.2 packages are downloaded to the same location, but there are some minor version differences in the underlying C libraries, which could break things. So, although it would work in a completely clean environment on any 4.2 version, it wouldn't work if you already have a specific minor version installed.

To disable the autoload of renv, I think the easiest way is to wrap the `.Rprofile` startup source call in an environment variable that prevents renv normally.

> At the same time, I would think that most researchers using the code will not have experience setting it up or not want the 15-45 min wait before running the code. I see a tradeoff here; and for merging to main it would be great to have the option to skip setting up the renv.

I agree. For local runtime, it would probably be better if we don't have people use renv just because of global vs local package environments conflicting with each other. Though, I think 15-45 minutes is a reasonable time to wait to have a perfectly working environment since we already wait hours for our queries to run or datasets to be transformed.

I will work on these two/three points tomorrow.

**Comment by ahaim5357** [comment]
Ok, I have updated everything to match what we've talked about, lmk if I should address something else.

**Comment by conradborchers** [comment]
Hi Aaron, sorry for the lag. I really appreciate your help in this. Could you perhaps help me step through one more error?

```
srl-cycles-lak24 % Rscript ./setup-lak24.R

Error in if (Sys.getenv("AUTOLOAD_RENV_DEVENV")) { : 
  argument is not interpretable as logical
Execution halted
```

Also, one thing you might have overlooked is the regex matching in your `setup.sh` script. It still does not match the transaction file for me. Could we perhaps do something like?

```
if [ "$(ls -A /path/to/directory)" ]; then
    echo "Directory is not empty"
else
    echo "Directory is empty"
fi
```

but with a match on the `.txt` file?

Thanks again! Happy to connect about this.

**Comment by ahaim5357** [comment]
> Hi Aaron, sorry for the lag. I really appreciate your help in this. Could you perhaps help me step through one more error?

Yep, this is just a simple bug to return a default if something is missing

> Also, one thing you might have overlooked is the regex matching in your `setup.sh` script. It still does not match the transaction file for me. Could we perhaps do something like?

It's weird because it matches fine, at least according to POSIX standard, so I'm not exactly sure what the issue is. If you have time today, I could jump into a meeting to debug this since I don't have a mac on me at the current moment. If not, I can try to requisition one next week.

**Comment by ahaim5357** [comment]
Ok, I think I pushed a fix. The documentation says I need to add `-E`, so I did so for mac implementations only.

**Comment by conradborchers** [comment]
Thanks, Aaron! We are really close. The only remaining error I am getting is for `setup.sh`:

```
srl-cycles-lak24 % bash setup.sh
sed: 1: "s/\(\(.*\/\)\?ds[0-9]\+ ...": \1 not defined in the RE
usage: mv [-f | -i | -n] [-hv] source target
       mv [-f | -i | -n] [-v] source ... directory
Renamed transactional file!
Missing one or more dataset files.
Please follow the steps under 'Setup' in the README to get started. Then run this script again.
```

Any thoughts about this error? Can you reproduce it on your machine?

Otherwise I tested everything and am ready to merge. Thanks again!

**Comment by ahaim5357** [comment]
This suggests there's a different syntax for Mac when determining groupings. Either that or there's something I missed during testing, which is a bit weird since it worked fine. I can take a look tomorrow.

**Comment by ahaim5357** [comment]
Ok, I figured it out. Apparently extended regex means that no regex commands need to be backslashed, which is very annoying, but now it should work without issue.

**Comment by conradborchers** [comment]
Thanks, Aaron! This worked for me. I appreciate you bearing with me. I will merge this pull request now. Have a great day.

**Pull request merged**
